// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package proto_pharmacy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestCityAndSource struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCityAndSource) Reset()         { *m = RequestCityAndSource{} }
func (m *RequestCityAndSource) String() string { return proto.CompactTextString(m) }
func (*RequestCityAndSource) ProtoMessage()    {}
func (*RequestCityAndSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *RequestCityAndSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCityAndSource.Unmarshal(m, b)
}
func (m *RequestCityAndSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCityAndSource.Marshal(b, m, deterministic)
}
func (m *RequestCityAndSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCityAndSource.Merge(m, src)
}
func (m *RequestCityAndSource) XXX_Size() int {
	return xxx_messageInfo_RequestCityAndSource.Size(m)
}
func (m *RequestCityAndSource) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCityAndSource.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCityAndSource proto.InternalMessageInfo

func (m *RequestCityAndSource) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type ResponseCities struct {
	Errors               *ErrorResponse `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	Cities               []*City        `protobuf:"bytes,2,rep,name=cities,proto3" json:"cities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseCities) Reset()         { *m = ResponseCities{} }
func (m *ResponseCities) String() string { return proto.CompactTextString(m) }
func (*ResponseCities) ProtoMessage()    {}
func (*ResponseCities) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *ResponseCities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCities.Unmarshal(m, b)
}
func (m *ResponseCities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCities.Marshal(b, m, deterministic)
}
func (m *ResponseCities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCities.Merge(m, src)
}
func (m *ResponseCities) XXX_Size() int {
	return xxx_messageInfo_ResponseCities.Size(m)
}
func (m *ResponseCities) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCities.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCities proto.InternalMessageInfo

func (m *ResponseCities) GetErrors() *ErrorResponse {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseCities) GetCities() []*City {
	if m != nil {
		return m.Cities
	}
	return nil
}

type ResponseSources struct {
	Errors               *ErrorResponse `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	Sources              []*Source      `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseSources) Reset()         { *m = ResponseSources{} }
func (m *ResponseSources) String() string { return proto.CompactTextString(m) }
func (*ResponseSources) ProtoMessage()    {}
func (*ResponseSources) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *ResponseSources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSources.Unmarshal(m, b)
}
func (m *ResponseSources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSources.Marshal(b, m, deterministic)
}
func (m *ResponseSources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSources.Merge(m, src)
}
func (m *ResponseSources) XXX_Size() int {
	return xxx_messageInfo_ResponseSources.Size(m)
}
func (m *ResponseSources) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSources.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSources proto.InternalMessageInfo

func (m *ResponseSources) GetErrors() *ErrorResponse {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseSources) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ErrorResponse struct {
	IsError              bool     `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *ErrorResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Filter struct {
	IsActive             bool     `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DateUpdatedLte       string   `protobuf:"bytes,2,opt,name=date_updated_lte,json=dateUpdatedLte,proto3" json:"date_updated_lte,omitempty"`
	DateUpdatedGte       string   `protobuf:"bytes,3,opt,name=date_updated_gte,json=dateUpdatedGte,proto3" json:"date_updated_gte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Filter) GetDateUpdatedLte() string {
	if m != nil {
		return m.DateUpdatedLte
	}
	return ""
}

func (m *Filter) GetDateUpdatedGte() string {
	if m != nil {
		return m.DateUpdatedGte
	}
	return ""
}

type RequestData struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	LastId               int64    `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Filters              *Filter  `protobuf:"bytes,4,opt,name=filters,proto3" json:"filters,omitempty"`
	CompetitorSource     string   `protobuf:"bytes,5,opt,name=competitor_source,json=competitorSource,proto3" json:"competitor_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestData) Reset()         { *m = RequestData{} }
func (m *RequestData) String() string { return proto.CompactTextString(m) }
func (*RequestData) ProtoMessage()    {}
func (*RequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *RequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestData.Unmarshal(m, b)
}
func (m *RequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestData.Marshal(b, m, deterministic)
}
func (m *RequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestData.Merge(m, src)
}
func (m *RequestData) XXX_Size() int {
	return xxx_messageInfo_RequestData.Size(m)
}
func (m *RequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestData proto.InternalMessageInfo

func (m *RequestData) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RequestData) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *RequestData) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RequestData) GetFilters() *Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *RequestData) GetCompetitorSource() string {
	if m != nil {
		return m.CompetitorSource
	}
	return ""
}

type ResponseData struct {
	Errors               *ErrorResponse `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	Limit                int64          `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	LastId               int64          `protobuf:"varint,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Filters              *Filter        `protobuf:"bytes,4,opt,name=filters,proto3" json:"filters,omitempty"`
	Goods                []*MainProduct `protobuf:"bytes,5,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseData) Reset()         { *m = ResponseData{} }
func (m *ResponseData) String() string { return proto.CompactTextString(m) }
func (*ResponseData) ProtoMessage()    {}
func (*ResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}

func (m *ResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseData.Unmarshal(m, b)
}
func (m *ResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseData.Marshal(b, m, deterministic)
}
func (m *ResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseData.Merge(m, src)
}
func (m *ResponseData) XXX_Size() int {
	return xxx_messageInfo_ResponseData.Size(m)
}
func (m *ResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseData proto.InternalMessageInfo

func (m *ResponseData) GetErrors() *ErrorResponse {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseData) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ResponseData) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *ResponseData) GetFilters() *Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ResponseData) GetGoods() []*MainProduct {
	if m != nil {
		return m.Goods
	}
	return nil
}

type MainProduct struct {
	Id                   int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CodeCvp              string           `protobuf:"bytes,2,opt,name=code_cvp,json=codeCvp,proto3" json:"code_cvp,omitempty"`
	ExternalId           string           `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ProtekCode           int64            `protobuf:"varint,4,opt,name=protek_code,json=protekCode,proto3" json:"protek_code,omitempty"`
	Barcode              string           `protobuf:"bytes,5,opt,name=barcode,proto3" json:"barcode,omitempty"`
	SourceId             int64            `protobuf:"varint,6,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Sku                  string           `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`
	Article              string           `protobuf:"bytes,8,opt,name=article,proto3" json:"article,omitempty"`
	Name                 string           `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Price                int64            `protobuf:"varint,10,opt,name=price,proto3" json:"price,omitempty"`
	PriceOld             int64            `protobuf:"varint,11,opt,name=price_old,json=priceOld,proto3" json:"price_old,omitempty"`
	IsActive             bool             `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Brand                string           `protobuf:"bytes,13,opt,name=brand,proto3" json:"brand,omitempty"`
	Url                  string           `protobuf:"bytes,14,opt,name=url,proto3" json:"url,omitempty"`
	Sale                 int64            `protobuf:"varint,15,opt,name=sale,proto3" json:"sale,omitempty"`
	CountFeedbacks       int64            `protobuf:"varint,16,opt,name=count_feedbacks,json=countFeedbacks,proto3" json:"count_feedbacks,omitempty"`
	Rating               int64            `protobuf:"varint,17,opt,name=rating,proto3" json:"rating,omitempty"`
	DateUpdated          string           `protobuf:"bytes,19,opt,name=date_updated,json=dateUpdated,proto3" json:"date_updated,omitempty"`
	Category             string           `protobuf:"bytes,20,opt,name=category,proto3" json:"category,omitempty"`
	CityId               int64            `protobuf:"varint,21,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	CompetitorGoods      []*DetailProduct `protobuf:"bytes,22,rep,name=competitor_goods,json=competitorGoods,proto3" json:"competitor_goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MainProduct) Reset()         { *m = MainProduct{} }
func (m *MainProduct) String() string { return proto.CompactTextString(m) }
func (*MainProduct) ProtoMessage()    {}
func (*MainProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}

func (m *MainProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainProduct.Unmarshal(m, b)
}
func (m *MainProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainProduct.Marshal(b, m, deterministic)
}
func (m *MainProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainProduct.Merge(m, src)
}
func (m *MainProduct) XXX_Size() int {
	return xxx_messageInfo_MainProduct.Size(m)
}
func (m *MainProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_MainProduct.DiscardUnknown(m)
}

var xxx_messageInfo_MainProduct proto.InternalMessageInfo

func (m *MainProduct) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MainProduct) GetCodeCvp() string {
	if m != nil {
		return m.CodeCvp
	}
	return ""
}

func (m *MainProduct) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *MainProduct) GetProtekCode() int64 {
	if m != nil {
		return m.ProtekCode
	}
	return 0
}

func (m *MainProduct) GetBarcode() string {
	if m != nil {
		return m.Barcode
	}
	return ""
}

func (m *MainProduct) GetSourceId() int64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *MainProduct) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *MainProduct) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *MainProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MainProduct) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MainProduct) GetPriceOld() int64 {
	if m != nil {
		return m.PriceOld
	}
	return 0
}

func (m *MainProduct) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *MainProduct) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *MainProduct) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *MainProduct) GetSale() int64 {
	if m != nil {
		return m.Sale
	}
	return 0
}

func (m *MainProduct) GetCountFeedbacks() int64 {
	if m != nil {
		return m.CountFeedbacks
	}
	return 0
}

func (m *MainProduct) GetRating() int64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *MainProduct) GetDateUpdated() string {
	if m != nil {
		return m.DateUpdated
	}
	return ""
}

func (m *MainProduct) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *MainProduct) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *MainProduct) GetCompetitorGoods() []*DetailProduct {
	if m != nil {
		return m.CompetitorGoods
	}
	return nil
}

type DetailProduct struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId             int64    `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Sku                  string   `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Article              string   `protobuf:"bytes,4,opt,name=article,proto3" json:"article,omitempty"`
	Relation             string   `protobuf:"bytes,5,opt,name=relation,proto3" json:"relation,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Price                int64    `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	PriceOld             int64    `protobuf:"varint,8,opt,name=price_old,json=priceOld,proto3" json:"price_old,omitempty"`
	IsActive             bool     `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Brand                string   `protobuf:"bytes,10,opt,name=brand,proto3" json:"brand,omitempty"`
	Url                  string   `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Sale                 int64    `protobuf:"varint,12,opt,name=sale,proto3" json:"sale,omitempty"`
	CountFeedbacks       int64    `protobuf:"varint,13,opt,name=count_feedbacks,json=countFeedbacks,proto3" json:"count_feedbacks,omitempty"`
	Rating               int64    `protobuf:"varint,14,opt,name=rating,proto3" json:"rating,omitempty"`
	DateUpdated          string   `protobuf:"bytes,16,opt,name=date_updated,json=dateUpdated,proto3" json:"date_updated,omitempty"`
	Category             string   `protobuf:"bytes,17,opt,name=category,proto3" json:"category,omitempty"`
	CityId               int64    `protobuf:"varint,18,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	Address              string   `protobuf:"bytes,19,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailProduct) Reset()         { *m = DetailProduct{} }
func (m *DetailProduct) String() string { return proto.CompactTextString(m) }
func (*DetailProduct) ProtoMessage()    {}
func (*DetailProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}

func (m *DetailProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailProduct.Unmarshal(m, b)
}
func (m *DetailProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailProduct.Marshal(b, m, deterministic)
}
func (m *DetailProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailProduct.Merge(m, src)
}
func (m *DetailProduct) XXX_Size() int {
	return xxx_messageInfo_DetailProduct.Size(m)
}
func (m *DetailProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailProduct.DiscardUnknown(m)
}

var xxx_messageInfo_DetailProduct proto.InternalMessageInfo

func (m *DetailProduct) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DetailProduct) GetSourceId() int64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *DetailProduct) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *DetailProduct) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *DetailProduct) GetRelation() string {
	if m != nil {
		return m.Relation
	}
	return ""
}

func (m *DetailProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetailProduct) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *DetailProduct) GetPriceOld() int64 {
	if m != nil {
		return m.PriceOld
	}
	return 0
}

func (m *DetailProduct) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *DetailProduct) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *DetailProduct) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DetailProduct) GetSale() int64 {
	if m != nil {
		return m.Sale
	}
	return 0
}

func (m *DetailProduct) GetCountFeedbacks() int64 {
	if m != nil {
		return m.CountFeedbacks
	}
	return 0
}

func (m *DetailProduct) GetRating() int64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *DetailProduct) GetDateUpdated() string {
	if m != nil {
		return m.DateUpdated
	}
	return ""
}

func (m *DetailProduct) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *DetailProduct) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *DetailProduct) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type City struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Source struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestCityAndSource)(nil), "proto_pharmacy.RequestCityAndSource")
	proto.RegisterType((*ResponseCities)(nil), "proto_pharmacy.ResponseCities")
	proto.RegisterType((*ResponseSources)(nil), "proto_pharmacy.ResponseSources")
	proto.RegisterType((*ErrorResponse)(nil), "proto_pharmacy.ErrorResponse")
	proto.RegisterType((*Filter)(nil), "proto_pharmacy.Filter")
	proto.RegisterType((*RequestData)(nil), "proto_pharmacy.RequestData")
	proto.RegisterType((*ResponseData)(nil), "proto_pharmacy.ResponseData")
	proto.RegisterType((*MainProduct)(nil), "proto_pharmacy.MainProduct")
	proto.RegisterType((*DetailProduct)(nil), "proto_pharmacy.DetailProduct")
	proto.RegisterType((*City)(nil), "proto_pharmacy.City")
	proto.RegisterType((*Source)(nil), "proto_pharmacy.Source")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 887 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0xdf, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0x9b, 0x38, 0x71, 0x92, 0x71, 0x93, 0xa6, 0x4b, 0x28, 0x4b, 0x0f, 0xb8, 0xc3, 0x42,
	0xa2, 0x82, 0x53, 0x81, 0x22, 0xde, 0x78, 0xa9, 0x7a, 0x5c, 0x08, 0x3f, 0xc4, 0xc9, 0xa7, 0x7b,
	0xb6, 0xb6, 0xde, 0xb9, 0xb0, 0x8a, 0x63, 0x9b, 0xdd, 0x75, 0x45, 0xf8, 0xbb, 0xf8, 0x5f, 0x10,
	0x6f, 0xfc, 0x23, 0x48, 0x68, 0x77, 0xed, 0x36, 0xae, 0x9b, 0x72, 0xd7, 0xa7, 0x78, 0x66, 0x67,
	0xbf, 0x33, 0x3b, 0xf3, 0xd9, 0xd8, 0x30, 0x2e, 0x64, 0xce, 0xcb, 0x44, 0x9f, 0x16, 0x32, 0xd7,
	0x39, 0x99, 0xd8, 0x9f, 0xb8, 0xf8, 0x95, 0xc9, 0x35, 0x4b, 0x36, 0xe1, 0x17, 0x30, 0x8b, 0xf0,
	0xb7, 0x12, 0x95, 0xbe, 0x10, 0x7a, 0x73, 0x9e, 0xf1, 0x97, 0x79, 0x29, 0x13, 0x24, 0xef, 0xc1,
	0x80, 0x15, 0x22, 0x5e, 0xe1, 0x86, 0x76, 0x9e, 0x74, 0x4e, 0x46, 0x91, 0xcf, 0x0a, 0xf1, 0x23,
	0x6e, 0xc2, 0x12, 0x26, 0x11, 0xaa, 0x22, 0xcf, 0x14, 0x5e, 0x08, 0x2d, 0x50, 0x91, 0x6f, 0xc0,
	0x47, 0x29, 0x73, 0xa9, 0x6c, 0x64, 0x70, 0xf6, 0xe1, 0x69, 0x33, 0xc7, 0xe9, 0x77, 0x66, 0xb5,
	0xde, 0x14, 0x55, 0xc1, 0xe4, 0x29, 0xf8, 0x89, 0x15, 0xa0, 0xdd, 0x27, 0xde, 0x49, 0x70, 0x36,
	0xbb, 0xbd, 0xcd, 0x14, 0x14, 0x55, 0x31, 0xe1, 0x1f, 0x70, 0x50, 0x2b, 0xb8, 0x0a, 0x1f, 0x9c,
	0xf7, 0x4b, 0x18, 0x28, 0xa7, 0x50, 0x25, 0x3e, 0xba, 0xbd, 0xcf, 0x25, 0x88, 0xea, 0xb0, 0xf0,
	0x5b, 0x18, 0x37, 0xa4, 0xc8, 0xfb, 0x30, 0x14, 0x2a, 0xb6, 0x7a, 0x36, 0xf7, 0x30, 0x1a, 0x08,
	0x65, 0x43, 0xc8, 0x14, 0xbc, 0xb5, 0x5a, 0xd2, 0xae, 0xed, 0x99, 0x79, 0x0c, 0x37, 0xe0, 0x3f,
	0x17, 0xa9, 0x46, 0x49, 0x1e, 0xc1, 0x48, 0xa8, 0x98, 0x25, 0x5a, 0x5c, 0x61, 0xb5, 0x6f, 0x28,
	0xd4, 0xb9, 0xb5, 0xc9, 0x09, 0x4c, 0x39, 0xd3, 0x18, 0x97, 0x85, 0xf9, 0xe1, 0x71, 0xaa, 0xb1,
	0x52, 0x99, 0x18, 0xc7, 0x2b, 0xe7, 0xfe, 0x49, 0xb7, 0x23, 0x97, 0x1a, 0xa9, 0xd7, 0x8a, 0x9c,
	0x6b, 0x0c, 0xff, 0xec, 0x40, 0x50, 0x4d, 0xf7, 0x19, 0xd3, 0x8c, 0xcc, 0xa0, 0x9f, 0x8a, 0xb5,
	0xd0, 0x36, 0xb9, 0x17, 0x39, 0xc3, 0x8c, 0x3a, 0x65, 0x4a, 0xc7, 0x82, 0xdb, 0x84, 0x5e, 0xe4,
	0x1b, 0x73, 0xc1, 0xb7, 0x19, 0xf0, 0xb6, 0x19, 0x30, 0x2d, 0x7c, 0x6d, 0x8f, 0xa4, 0x68, 0xcf,
	0xb6, 0xbe, 0xd5, 0x42, 0x77, 0xe2, 0xa8, 0x0e, 0x23, 0x9f, 0xc3, 0x61, 0x92, 0xaf, 0x0b, 0xd4,
	0x42, 0xe7, 0x32, 0x76, 0x8d, 0xa5, 0x7d, 0x2b, 0x3a, 0xbd, 0x59, 0x70, 0x8d, 0x0f, 0xff, 0xee,
	0xc0, 0x7e, 0xdd, 0x6b, 0x5b, 0xf7, 0x03, 0x27, 0x7d, 0x7d, 0xdc, 0xee, 0x8e, 0xe3, 0x7a, 0x8d,
	0xe3, 0xbe, 0xfd, 0xa9, 0xbe, 0x82, 0xfe, 0x32, 0xcf, 0xb9, 0xa2, 0x7d, 0x0b, 0xd2, 0xa3, 0xdb,
	0xf1, 0x3f, 0x33, 0x91, 0xbd, 0x70, 0xd7, 0x2f, 0x72, 0x91, 0xe1, 0x3f, 0x3d, 0x08, 0xb6, 0xdc,
	0x64, 0x02, 0x5d, 0xc1, 0xab, 0x79, 0x74, 0x05, 0x37, 0x68, 0x25, 0x39, 0xc7, 0x38, 0xb9, 0x2a,
	0xaa, 0xf1, 0x0f, 0x8c, 0x7d, 0x71, 0x55, 0x90, 0xc7, 0x10, 0xe0, 0xef, 0x1a, 0x65, 0xc6, 0xd2,
	0xba, 0xf8, 0x51, 0x04, 0xb5, 0x6b, 0xc1, 0x4d, 0x80, 0x29, 0x00, 0x57, 0xb1, 0xd9, 0x62, 0x0f,
	0xe1, 0x45, 0xe0, 0x5c, 0x17, 0x39, 0x47, 0x42, 0x61, 0x70, 0xc9, 0xa4, 0x5d, 0x74, 0xbd, 0xaf,
	0x4d, 0x83, 0xa6, 0x1b, 0x8a, 0x51, 0xf6, 0xed, 0xc6, 0xa1, 0x73, 0x2c, 0xb8, 0x61, 0x5a, 0xad,
	0x4a, 0x3a, 0x70, 0x4c, 0xab, 0x55, 0x69, 0x84, 0x98, 0xd4, 0x22, 0x49, 0x91, 0x0e, 0x9d, 0x50,
	0x65, 0x12, 0x02, 0xbd, 0x8c, 0xad, 0x91, 0x8e, 0xac, 0xdb, 0x3e, 0x9b, 0x39, 0x14, 0x52, 0x24,
	0x48, 0xc1, 0xcd, 0xc1, 0x1a, 0x26, 0xa5, 0x7d, 0x88, 0xf3, 0x94, 0xd3, 0xc0, 0xa5, 0xb4, 0x8e,
	0x5f, 0x52, 0xde, 0xbc, 0x2a, 0xfb, 0xb7, 0xae, 0xca, 0x0c, 0xfa, 0x97, 0x92, 0x65, 0x9c, 0x8e,
	0x6d, 0x12, 0x67, 0x98, 0x2a, 0x4b, 0x99, 0xd2, 0x89, 0xab, 0xb2, 0x94, 0xa9, 0xa9, 0x45, 0xb1,
	0x14, 0xe9, 0x81, 0x15, 0xb7, 0xcf, 0xe4, 0x53, 0x38, 0x48, 0xf2, 0x32, 0xd3, 0xf1, 0x6b, 0x44,
	0x7e, 0xc9, 0x92, 0x95, 0xa2, 0x53, 0xbb, 0x3c, 0xb1, 0xee, 0xe7, 0xb5, 0x97, 0x1c, 0x81, 0x2f,
	0x99, 0x16, 0xd9, 0x92, 0x1e, 0x3a, 0x4a, 0x9c, 0x45, 0x3e, 0x86, 0xfd, 0xed, 0xdb, 0x47, 0xdf,
	0xb1, 0xf9, 0x82, 0xad, 0x9b, 0x47, 0x8e, 0x61, 0x98, 0x30, 0x8d, 0xcb, 0x5c, 0x6e, 0xe8, 0xcc,
	0x2e, 0x5f, 0xdb, 0x86, 0xbe, 0x44, 0xe8, 0x8d, 0x69, 0xf3, 0xbb, 0x4e, 0xd7, 0x98, 0x0b, 0x4e,
	0xbe, 0x87, 0xad, 0x8b, 0x10, 0x3b, 0xac, 0x8e, 0x2c, 0x56, 0x2d, 0xda, 0x9f, 0xa1, 0x66, 0x22,
	0xad, 0xc1, 0x3a, 0xb8, 0xd9, 0x36, 0xb7, 0x88, 0xfd, 0xe5, 0xc1, 0xb8, 0x11, 0xd2, 0x82, 0xac,
	0x31, 0xed, 0xee, 0xdd, 0xd3, 0xf6, 0xee, 0x9c, 0x76, 0xaf, 0x39, 0xed, 0x63, 0x18, 0x4a, 0x4c,
	0x99, 0x16, 0x79, 0x56, 0x11, 0x75, 0x6d, 0x5f, 0x93, 0xe0, 0xdf, 0x45, 0xc2, 0x60, 0x27, 0x09,
	0xc3, 0xfb, 0x48, 0x18, 0xed, 0x22, 0x01, 0xee, 0x20, 0x21, 0x68, 0x93, 0xb0, 0x7f, 0x3f, 0x09,
	0xe3, 0xff, 0x21, 0x61, 0x72, 0x2f, 0x09, 0xd3, 0xfb, 0x49, 0x38, 0xdc, 0x4d, 0x02, 0x69, 0x90,
	0x60, 0xda, 0xcd, 0xb9, 0x44, 0xa5, 0x2a, 0xb8, 0x6a, 0x33, 0xfc, 0x0c, 0x7a, 0xe6, 0xa5, 0xd8,
	0x9a, 0x67, 0xdd, 0xea, 0xee, 0x4d, 0xab, 0xc3, 0xa7, 0xe0, 0x57, 0xaf, 0xf2, 0x37, 0x88, 0x3e,
	0xfb, 0xb7, 0x03, 0xde, 0xf9, 0x8b, 0x05, 0xf9, 0x01, 0x82, 0x39, 0xea, 0x8a, 0x1b, 0x45, 0x5a,
	0xff, 0x68, 0x5b, 0x6f, 0x93, 0xe3, 0x0f, 0xda, 0x8b, 0x37, 0xff, 0xd9, 0xe1, 0x1e, 0x79, 0x09,
	0xa3, 0x39, 0xea, 0xea, 0x23, 0xe1, 0x93, 0x1d, 0x4a, 0x8d, 0xaf, 0x8e, 0xe3, 0x8f, 0x76, 0x49,
	0x3a, 0x95, 0x70, 0x8f, 0xbc, 0x02, 0x98, 0xa3, 0xae, 0x3f, 0x01, 0xde, 0x4c, 0xf5, 0xf1, 0x2e,
	0xd5, 0x4a, 0x26, 0xdc, 0xbb, 0xf4, 0x6d, 0xc4, 0xd7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf1,
	0x0d, 0xc0, 0x91, 0x2e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	GetProducts(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (*ResponseData, error)
	GetCities(ctx context.Context, in *RequestCityAndSource, opts ...grpc.CallOption) (*ResponseCities, error)
	GetSources(ctx context.Context, in *RequestCityAndSource, opts ...grpc.CallOption) (*ResponseSources, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetProducts(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (*ResponseData, error) {
	out := new(ResponseData)
	err := c.cc.Invoke(ctx, "/proto_pharmacy.API/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetCities(ctx context.Context, in *RequestCityAndSource, opts ...grpc.CallOption) (*ResponseCities, error) {
	out := new(ResponseCities)
	err := c.cc.Invoke(ctx, "/proto_pharmacy.API/GetCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetSources(ctx context.Context, in *RequestCityAndSource, opts ...grpc.CallOption) (*ResponseSources, error) {
	out := new(ResponseSources)
	err := c.cc.Invoke(ctx, "/proto_pharmacy.API/GetSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	GetProducts(context.Context, *RequestData) (*ResponseData, error)
	GetCities(context.Context, *RequestCityAndSource) (*ResponseCities, error)
	GetSources(context.Context, *RequestCityAndSource) (*ResponseSources, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) GetProducts(ctx context.Context, req *RequestData) (*ResponseData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (*UnimplementedAPIServer) GetCities(ctx context.Context, req *RequestCityAndSource) (*ResponseCities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCities not implemented")
}
func (*UnimplementedAPIServer) GetSources(ctx context.Context, req *RequestCityAndSource) (*ResponseSources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSources not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_pharmacy.API/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetProducts(ctx, req.(*RequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCityAndSource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_pharmacy.API/GetCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetCities(ctx, req.(*RequestCityAndSource))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCityAndSource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_pharmacy.API/GetSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetSources(ctx, req.(*RequestCityAndSource))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_pharmacy.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _API_GetProducts_Handler,
		},
		{
			MethodName: "GetCities",
			Handler:    _API_GetCities_Handler,
		},
		{
			MethodName: "GetSources",
			Handler:    _API_GetSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
